[tool.poetry]
name = "mi-proyecto"
version = "0.1.0"
description = "Descripción del proyecto."
authors = ["Mi Nombre <miemail@example.com>"]

[tool.poetry.dependencies]
python = "^3.9"
numpy = "^1.22.2"
pandas = "^1.3.5"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
