@startuml

class Matriz {
  - elementos: List[List[int]]
  + __init__(elementos: List[List[int]])
  + __add__(otra_matriz: Matriz) -> Matriz
  + __sub__(otra_matriz: Matriz) -> Matriz
  + __mul__(escalar: int) -> Matriz
}

class Determinante {
  - matriz: Matriz
  + __init__(matriz: Matriz)
  + calcular() -> int
}

class Menu {
  - opciones: Dict[str, Callable[[], Any]]
  + __init__()
  + agregar_opcion(nombre: str, funcion: Callable[[], Any])
  + mostrar()
}

Matriz *-- Determinante
Menu o-- "1" Matriz

@enduml
